[2025-06-30 14:43:14,905] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 14:43:14,914] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 14:43:17,021] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 14:43:17,021] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 14:43:17,481] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 14:43:17,506] INFO inference.apps - Прогрев Whisper...
[2025-06-30 14:43:17,525] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 14:43:17,525] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 14:43:33,873] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 14:43:54,158] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 14:43:54,158] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 14:43:55,625] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 14:43:55,625] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 14:43:56,251] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 14:43:56,319] INFO inference.apps - Прогрев Whisper...
[2025-06-30 14:43:56,406] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 14:43:56,411] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 14:43:58,848] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 14:43:58,982] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-06-30 14:46:00,395] WARNING django.request - Not Found: /favicon.ico
[2025-06-30 14:46:08,423] INFO inference.views - Получен запрос на распознавание: файл=rec.webm, модель=wav2vec2, язык=ru
[2025-06-30 14:46:09,108] INFO inference.services.preprocess - MP3 разбит на 1 WAV-кусков по 300 с
[2025-06-30 14:46:15,902] INFO inference.services.preprocess - Сохранено чанков: 1
[2025-06-30 14:46:15,904] INFO inference.services.preprocess - Готово: 1 финальных WAV-фрагментов по <= 10 с
[2025-06-30 14:46:15,904] INFO inference.views - Аудиофайл разбит на 1 чанков.
[2025-06-30 14:46:15,905] INFO inference.views - Обработка чанка 1/1
[2025-06-30 14:46:15,905] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 14:46:17,804] INFO inference.services.postprocess - Temp очищен
[2025-06-30 14:46:17,805] INFO inference.views - Обработка завершена
[2025-06-30 14:46:25,359] INFO inference.views - Получен запрос на распознавание: файл=rec.webm, модель=wav2vec2, язык=ru
[2025-06-30 14:46:25,474] INFO inference.services.preprocess - MP3 разбит на 1 WAV-кусков по 300 с
[2025-06-30 14:46:25,488] INFO inference.services.preprocess - Сохранено чанков: 1
[2025-06-30 14:46:25,488] INFO inference.services.preprocess - Готово: 1 финальных WAV-фрагментов по <= 10 с
[2025-06-30 14:46:25,488] INFO inference.views - Аудиофайл разбит на 1 чанков.
[2025-06-30 14:46:25,490] INFO inference.views - Обработка чанка 1/1
[2025-06-30 14:46:25,490] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 14:46:25,891] INFO inference.services.postprocess - Temp очищен
[2025-06-30 14:46:25,892] INFO inference.views - Обработка завершена
[2025-06-30 14:46:32,306] INFO inference.views - Получен запрос на распознавание: файл=rec.webm, модель=whisper, язык=ru
[2025-06-30 14:46:32,403] INFO inference.services.preprocess - MP3 разбит на 1 WAV-кусков по 300 с
[2025-06-30 14:46:32,416] INFO inference.services.preprocess - Сохранено чанков: 1
[2025-06-30 14:46:32,416] INFO inference.services.preprocess - Готово: 1 финальных WAV-фрагментов по <= 10 с
[2025-06-30 14:46:32,417] INFO inference.views - Аудиофайл разбит на 1 чанков.
[2025-06-30 14:46:32,417] INFO inference.views - Обработка чанка 1/1
[2025-06-30 14:46:45,807] INFO inference.services.postprocess - Temp очищен
[2025-06-30 14:46:45,811] INFO inference.views - Обработка завершена
[2025-06-30 14:47:45,783] WARNING django.request - Not Found: /accounts/login/
[2025-06-30 14:47:54,980] WARNING django.request - Not Found: /accounts/
[2025-06-30 14:48:00,412] WARNING django.request - Not Found: /login
[2025-06-30 14:48:09,537] ERROR django.request - Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\forms\forms.py", line 206, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\forms\forms.py", line 201, in errors
    self.full_clean()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\forms\forms.py", line 338, in full_clean
    self._clean_form()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\forms\forms.py", line 354, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\forms.py", line 366, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: auth_user
[2025-06-30 14:54:08,873] WARNING django.request - Not Found: /favicon.ico
[2025-06-30 14:54:32,356] ERROR django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[2025-06-30 14:57:15,290] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 14:57:15,291] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 14:57:16,134] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 14:57:16,135] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 14:57:16,473] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 14:57:16,484] INFO inference.apps - Прогрев Whisper...
[2025-06-30 14:57:16,500] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 14:57:16,501] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 14:57:31,484] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 14:57:45,750] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 14:57:45,751] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 14:57:46,556] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 14:57:46,556] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 14:57:47,003] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 14:57:47,011] INFO inference.apps - Прогрев Whisper...
[2025-06-30 14:57:47,031] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 14:57:47,031] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 14:57:48,293] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 14:57:48,331] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-06-30 15:00:33,491] ERROR django.request - Internal Server Error: /api/transcribe/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[2025-06-30 15:00:36,130] ERROR django.request - Internal Server Error: /api/transcribe/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[2025-06-30 15:00:37,554] ERROR django.request - Internal Server Error: /api/transcribe/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[2025-06-30 15:00:39,455] ERROR django.request - Internal Server Error: /api/transcribe/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[2025-06-30 15:00:40,448] ERROR django.request - Internal Server Error: /api/transcribe/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\rest_framework\authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[2025-06-30 15:01:52,877] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:01:52,877] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:01:53,601] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:01:53,602] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:01:53,843] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:01:53,850] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:01:53,870] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:01:53,870] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:02:03,465] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:02:20,312] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:02:20,314] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:02:21,523] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:02:21,524] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:02:21,872] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:02:21,876] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:02:22,010] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:02:22,010] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:02:23,186] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:02:23,231] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-06-30 15:02:37,284] ERROR django.request - Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\forms\forms.py", line 206, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\forms\forms.py", line 201, in errors
    self.full_clean()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\forms\forms.py", line 338, in full_clean
    self._clean_form()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\forms\forms.py", line 354, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\forms.py", line 366, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: auth_user
[2025-06-30 15:02:47,222] INFO inference.views - Получен запрос на распознавание: файл=rec.webm, модель=wav2vec2, язык=ru
[2025-06-30 15:02:47,497] INFO inference.services.preprocess - MP3 разбит на 1 WAV-кусков по 300 с
[2025-06-30 15:02:51,715] INFO inference.services.preprocess - Сохранено чанков: 1
[2025-06-30 15:02:51,716] INFO inference.services.preprocess - Готово: 1 финальных WAV-фрагментов по <= 10 с
[2025-06-30 15:02:51,717] INFO inference.views - Аудиофайл разбит на 1 чанков.
[2025-06-30 15:02:51,718] INFO inference.views - Обработка чанка 1/1
[2025-06-30 15:02:51,718] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:02:52,276] INFO inference.services.postprocess - Temp очищен
[2025-06-30 15:02:52,276] INFO inference.views - Обработка завершена
[2025-06-30 15:02:59,271] INFO inference.views - Получен запрос на распознавание: файл=rec.webm, модель=whisper, язык=ru
[2025-06-30 15:02:59,380] INFO inference.services.preprocess - MP3 разбит на 1 WAV-кусков по 300 с
[2025-06-30 15:02:59,401] INFO inference.services.preprocess - Сохранено чанков: 1
[2025-06-30 15:02:59,402] INFO inference.services.preprocess - Готово: 1 финальных WAV-фрагментов по <= 10 с
[2025-06-30 15:02:59,402] INFO inference.views - Аудиофайл разбит на 1 чанков.
[2025-06-30 15:02:59,402] INFO inference.views - Обработка чанка 1/1
[2025-06-30 15:03:14,456] INFO inference.services.postprocess - Temp очищен
[2025-06-30 15:03:14,465] INFO inference.views - Обработка завершена
[2025-06-30 15:03:37,671] ERROR django.request - Internal Server Error: /admin/
Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ВКР\project\asr_project\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[2025-06-30 15:15:40,325] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:15:40,325] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:15:43,846] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:15:43,873] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:15:45,560] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:15:45,579] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:15:45,602] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:15:45,603] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:16:04,216] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:17:22,428] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:17:22,428] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:17:23,204] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:17:23,206] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:17:23,468] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:17:23,476] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:17:23,493] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:17:23,494] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:17:27,883] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:18:23,850] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:18:23,851] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:18:25,026] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:18:25,028] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:18:25,517] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:18:25,520] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:18:25,533] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:18:25,534] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:18:26,660] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:18:49,969] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:18:49,970] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:18:50,848] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:18:50,848] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:18:51,130] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:18:51,134] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:18:51,145] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:18:51,146] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:18:52,171] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:19:46,946] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:19:46,947] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:19:47,566] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:19:47,566] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:19:47,778] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:19:47,785] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:19:47,796] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:19:47,797] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:19:48,725] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:19:57,187] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:19:57,187] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:19:57,781] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:19:57,781] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:19:58,037] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:19:58,041] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:19:58,056] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:19:58,057] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:19:59,214] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:19:59,295] INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-06-30 15:20:06,604] WARNING django.request - Not Found: /favicon.ico
[2025-06-30 15:20:33,847] INFO inference.views - Получен запрос на распознавание: файл=rec.webm, модель=whisper, язык=ru
[2025-06-30 15:20:34,130] INFO inference.services.preprocess - MP3 разбит на 1 WAV-кусков по 300 с
[2025-06-30 15:20:38,116] INFO inference.services.preprocess - Сохранено чанков: 1
[2025-06-30 15:20:38,116] INFO inference.services.preprocess - Готово: 1 финальных WAV-фрагментов по <= 10 с
[2025-06-30 15:20:38,119] INFO inference.views - Аудиофайл разбит на 1 чанков.
[2025-06-30 15:20:38,119] INFO inference.views - Обработка чанка 1/1
[2025-06-30 15:20:50,842] INFO inference.services.postprocess - Temp очищен
[2025-06-30 15:20:50,846] INFO inference.views - Обработка завершена
[2025-06-30 15:22:14,685] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:22:14,687] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:22:15,303] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:22:15,304] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:22:15,542] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:22:15,547] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:22:15,563] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:22:15,564] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:22:17,796] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:22:31,358] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:22:31,359] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:22:32,010] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:22:32,010] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:22:32,215] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:22:32,219] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:22:32,230] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:22:32,231] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:22:33,125] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:23:36,333] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:23:36,334] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:23:37,124] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:23:37,125] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:23:37,416] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:23:37,421] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:23:37,431] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:23:37,431] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:23:38,603] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:23:47,125] INFO inference.apps - Старт загрузки моделей при запуске Django...
[2025-06-30 15:23:47,126] INFO inference.services.recognize_whisper - Загрузка модели Whisper...
[2025-06-30 15:23:47,833] INFO inference.services.recognize_whisper - Модель Whisper загружена.
[2025-06-30 15:23:47,834] INFO inference.services.recognize_wav2vec - Загрузка модели Wav2Vec2...
[2025-06-30 15:23:48,151] INFO inference.services.recognize_wav2vec - Модель Wav2Vec2 загружена.
[2025-06-30 15:23:48,154] INFO inference.apps - Прогрев Whisper...
[2025-06-30 15:23:48,166] INFO inference.apps - Прогрев Wav2Vec2...
[2025-06-30 15:23:48,167] INFO inference.services.recognize_wav2vec - Распознавание Wav2Vec2
[2025-06-30 15:23:49,366] INFO inference.apps - Модели успешно загружены и прогреты при старте Django.
[2025-06-30 15:23:49,403] INFO django.utils.autoreload - Watching for file changes with StatReloader
